plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
yarnPath: .yarn/releases/yarn-3.2.2.cjs
packageExtensions:
  '@remix-run/dev@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@remix-run/express@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@remix-run/node@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@remix-run/serve@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
