services:
  db:
    build:
      context: .
      dockerfile: db/Containerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  api:
    image: postgrest/postgrest
    ports:
      - "${PGRST_PORT:-3000}:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/funicular
      PGRST_DB_SCHEMAS: "public"
      PGRST_DB_ANON_ROLE: "${PGRST_ANON:-anon}"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:${PGRST_PORT:-3000}"
    depends_on:
      - db

  openapi:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: "http://localhost:${PGRST_PORT:-3000}/"
    depends_on:
      - api

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
