// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/actors.tsx";
import * as $2 from "./routes/actors/[id].tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/counter.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/actors.tsx": $1,
    "./routes/actors/[id].tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
