FROM rust:1.72.0 AS build

RUN apt update
RUN apt install -y clang

WORKDIR /funicular
COPY . .
RUN cargo install --locked cargo-pgrx@0.10.0
RUN cargo pgrx init --pg16 download
RUN cargo pgrx package --manifest-path db/Cargo.toml --pg-config /root/.pgrx/16.0/pgrx-install/bin/pg_config --out-dir .

FROM postgres:16
COPY --from=build /funicular/root/.pgrx/16.0/pgrx-install/share/postgresql/extension/* /usr/share/postgresql/16/extension/
COPY --from=build /funicular/root/.pgrx/16.0/pgrx-install/lib/postgresql/funicular_db.so /usr/lib/postgresql/16/lib/
