FROM rust:1.69.0 AS build

RUN apt update
RUN apt install -y clang

WORKDIR /funicular
COPY . .
RUN cargo install --locked cargo-pgrx
RUN cargo pgrx init --pg15 download
RUN cargo pgrx package --manifest-path db/Cargo.toml --pg-config /root/.pgrx/15.3/pgrx-install/bin/pg_config --out-dir .

WORKDIR /pg_graphql
RUN git clone https://github.com/supabase/pg_graphql.git .
RUN cargo pgrx package --pg-config /root/.pgrx/15.3/pgrx-install/bin/pg_config --out-dir .

FROM postgres:15
COPY --from=build /funicular/root/.pgrx/15.3/pgrx-install/share/postgresql/extension/* /usr/share/postgresql/15/extension/
COPY --from=build /funicular/root/.pgrx/15.3/pgrx-install/lib/postgresql/funicular_db.so /usr/lib/postgresql/15/lib/
COPY --from=build /pg_graphql/root/.pgrx/15.3/pgrx-install/share/postgresql/extension/* /usr/share/postgresql/15/extension/
COPY --from=build /pg_graphql/root/.pgrx/15.3/pgrx-install/lib/postgresql/pg_graphql.so /usr/lib/postgresql/15/lib/
