FROM rust:1.71.0 AS build

RUN apt update
RUN apt install -y clang

WORKDIR /funicular
COPY . .
RUN cargo install --locked cargo-pgrx@0.9.8
RUN cargo pgrx init --pg15 download
RUN cargo pgrx package --manifest-path db/Cargo.toml --pg-config /root/.pgrx/15.4/pgrx-install/bin/pg_config --out-dir .

FROM postgres:15
COPY --from=build /funicular/root/.pgrx/15.4/pgrx-install/share/postgresql/extension/* /usr/share/postgresql/15/extension/
COPY --from=build /funicular/root/.pgrx/15.4/pgrx-install/lib/postgresql/funicular_db.so /usr/lib/postgresql/15/lib/
